# Generated by Django 4.1.1 on 2022-10-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=213, verbose_name='Возраст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='locic',
            field=models.BooleanField(verbose_name='Автор'),
        ),
    ]
