# Generated by Django 4.1.1 on 2022-10-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_person_age_alter_person_locic'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='test',
            field=models.IntegerField(default=None, verbose_name='test'),
        ),
    ]
